{% set version = "5.1-6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gamlss
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gamlss_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gamlss/gamlss_{{ version }}.tar.gz
  sha256: b9c9a21343ed7777c239d8c5ad63b6f6efa0254bfcd6eaf66a74c319268b6799

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-gamlss.data >=5.0_0
    - r-gamlss.dist >=4.3.1
    - r-nlme
    - r-survival
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-mass
    - r-gamlss.data >=5.0_0
    - r-gamlss.dist >=4.3.1
    - r-nlme
    - r-survival

test:
  commands:
    - $R -e "library('gamlss')"           # [not win]
    - "\"%R%\" -e \"library('gamlss')\""  # [win]

about:
  home: http://www.gamlss.org/
  license: GPL-2 | GPL-3
  summary: Functions for fitting the Generalized Additive Models for Location Scale and Shape
    introduced by Rigby and Stasinopoulos (2005), <doi:10.1111/j.1467-9876.2005.00510.x>.
    The models use a distributional regression approach where all the parameters of
    the conditional distribution of the response variable are modelled using explanatory
    variables.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: gamlss
# Description: Functions for fitting the Generalized Additive Models for Location Scale and Shape introduced by Rigby and Stasinopoulos (2005), <doi:10.1111/j.1467-9876.2005.00510.x>. The models use a distributional regression approach where all the parameters of the conditional distribution of the response variable are modelled using explanatory variables.
# Version: 5.1-4
# Date: 2019-05-18
# Authors@R: c(person("Mikis", "Stasinopoulos", role = c("aut", "cre", "cph"),  email = "d.stasinopoulos@londonmet.ac.uk"), person("Bob", "Rigby", role = c("aut")),  person("Vlasios", "Voudouris", role = "ctb",   email= "vlasios.voudouris@abm-analytics.com"), person("Calliope", "Akantziliotou", role = "ctb"), person("Marco", "Enea", role = "ctb"), person("Daniil", "Kiose", role = "ctb")  )
# Title: Generalised Additive Models for Location Scale and Shape
# Maintainer: Mikis Stasinopoulos <d.stasinopoulos@londonmet.ac.uk>
# Depends: R (>= 3.3.0), graphics, stats, splines, utils, grDevices, gamlss.data (>= 5.0-0), gamlss.dist (>= 4.3.1), nlme, parallel
# LazyLoad: yes
# Imports: MASS, survival, methods
# License: GPL-2 | GPL-3
# URL: http://www.gamlss.org/
# NeedsCompilation: yes
# Packaged: 2019-05-18 08:35:01 UTC; MikisStasinopoulos
# Author: Mikis Stasinopoulos [aut, cre, cph], Bob Rigby [aut], Vlasios Voudouris [ctb], Calliope Akantziliotou [ctb], Marco Enea [ctb], Daniil Kiose [ctb]
# Repository: CRAN
# Date/Publication: 2019-05-18 09:10:03 UTC
